#put any key/value pairs here
plugin.name=Mail Catcher
my.plugin.section.label=Mail Catcher
my.plugin.admin.section.label=Mail Catcher (Admin)
test.logger.servlet=Test Logger Servlet
mail.viewer.servlet=Mail Viewer
web.item.test.logger.servlet=web_item_test_logger_servlet
web.item.mail.viewer.servlet=web_item_mail_viewer_servlet
